language: python
python:
  - "3.6"
env:
    - DJANGO=1.11
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install django --upgrade
  - pip install djangorestframework
# command to run tests
script:
  - python manage.py test